In [1]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\Asus\anaconda3\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Asus\anaconda3\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\Asus\anaconda3\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\Asus\anaconda3\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\Asus\anaconda3\Lib\site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\Asus\anaconda3\Lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

# Label Encoding

In [1]:
from sklearn.preprocessing import LabelEncoder

In [5]:
products = ["Key", "Mouse", "Laptop", "Pendrive", "Laptop"]
encoder = LabelEncoder()
encoded_prods = encoder.fit_transform(products)
encoded_prods

array([0, 2, 1, 3, 1])

In [4]:
import pandas as pd

# gender = ["Male", "Female", "Male", "Female", "Male"]
# gender_df = pd.DataFrame(gender, columns=["Gender"])

gender_df = pd.DataFrame({
    "Gender" : ["Male", "Female", "Male", "Female", "Male"]
})

encoded_genders = encoder.fit_transform(gender_df["Gender"])
encoded_genders

array([1, 0, 1, 0, 1])

# One Hot Encoding

In [8]:
# from sklearn.preprocessing import OneHotEncoder
import pandas as pd

color = pd.DataFrame({
    "Color": ["Red", "Blue", "Yellow", "Red"]
})

encoded_colors = pd.get_dummies(color, columns=["Color"])
encoded_colors

   Color_Blue  Color_Red  Color_Yellow
0       False       True         False
1        True      False         False
2       False      False          True
3       False       True         False

In [9]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

color = pd.DataFrame({
    "Color": ["Red", "Blue", "Yellow", "Red"]
})
encoder = OneHotEncoder(sparse_output=False) # Setting to false will disable regular array output and gives sparse matrix output
encoded_colors = encoder.fit_transform(color[["Color"]])
encoded_colors

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [16]:
color = pd.DataFrame({
    "Color": ["Red", "Blue", "Yellow", "Red"]
})
encoder = OneHotEncoder(sparse_output=False)
encoded_colors = encoder.fit_transform(color[["Color"]])
encoded_df = pd.DataFrame(
    encoded_colors,
    columns = encoder.get_feature_names_out(["Color"])
)

encoded_df
# [1001, 0100, 0010, 1001]

   Color_Blue  Color_Red  Color_Yellow
0         0.0        1.0           0.0
1         1.0        0.0           0.0
2         0.0        0.0           1.0
3         0.0        1.0           0.0

# Ordinal Encoding

In [11]:
from sklearn.preprocessing import OrdinalEncoder
data = pd.DataFrame({
    "Qualifications": ["Bachelors", "School", "PHD", "Masters"]
})
encoder = OrdinalEncoder(categories=[["School", "Bachelors", "Masters", "PHD"]])

data["Ordered Qualifications"] = encoder.fit_transform(data[["Qualifications"]])
data

  Qualifications  Ordered Qualifications
0      Bachelors                     1.0
1         School                     0.0
2            PHD                     3.0
3        Masters                     2.0