In [2]:
import pandas as pd

In [4]:
df = pd.read_csv(r"Training_center.csv")
df.head()

,Student_ID,Program,Batch,City,Trainer,Gender,Course_Level,Learning_Mode,Month,Attendance_Percent,Assignments_Completed,Assessment_Score,Fees_Paid,Feedback_Rating,Placement_Status
0,STU1001,Power BI,ANP-D3679,Trichy,Karthik,Male,Beginner,Hybrid,August,89,10,98,18000,5.0,In Progress
1,STU1002,SQL & Database,ANP-D3676,Trichy,Arun,Female,Advanced,Hybrid,July,75,16,95,18000,4.0,In Progress
2,STU1003,AI & Machine Learning,ANP-D3680,Trichy,Karthik,Male,Intermediate,Hybrid,January,93,10,61,20000,3.0,Not Placed
3,STU1004,SQL & Database,ANP-D3678,Trichy,Priya,Female,Intermediate,Hybrid,August,91,16,68,25000,4.0,Not Placed
4,STU1005,SQL & Database,ANP-D3678,Salem,Divya,Male,Beginner,Classroom,April,97,17,83,20000,5.0,In Progress

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             500 non-null    str
 1   Program                500 non-null    str
 2   Batch                  500 non-null    str
 3   City                   500 non-null    str
 4   Trainer                500 non-null    str
 5   Gender                 500 non-null    str
 6   Course_Level           500 non-null    str
 7   Learning_Mode          500 non-null    str
 8   Month                  500 non-null    str
 9   Attendance_Percent     500 non-null    int64
 10  Assignments_Completed  500 non-null    int64
 11  Assessment_Score       500 non-null    int64
 12  Fees_Paid              500 non-null    int64
 13  Feedback_Rating        500 non-null    float64
 14  Placement_Status       500 non-null    str
dtypes: float64(1), int64(4), str(10)
memory usage: 97.3 KB

In [11]:
prgrm_by_student = df.pivot_table(
    columns="Program",
    values="Student_ID",
    aggfunc="count"
)

prgrm_by_student

Program,AI & Machine Learning,Data Analytics,Power BI,Python Development,SQL & Database
Student_ID,91,109,112,95,93

In [13]:
prgrm_by_student = prgrm_by_student.rename(
    columns={"Student_ID": "student_count"}
)
prgrm_by_student

Program,AI & Machine Learning,Data Analytics,Power BI,Python Development,SQL & Database
Student_ID,91,109,112,95,93

In [14]:
program_gender = df.pivot_table(
    index = "Program",
    columns = "Gender",
    values = "Student_ID",
    aggfunc = 'count'
)

program_gender

Gender                 Female  Male
Program
AI & Machine Learning      43    48
Data Analytics             48    61
Power BI                   47    65
Python Development         46    49
SQL & Database             54    39