In [2]:
import pandas as pd

df = pd.read_csv(r"library_book.csv")
df.head()

,Transaction_ID,Student_ID,Student_Name,Department,Book_ID,Book_Title,Book_Category,Book_Price,Borrow_Date,Due_Date,Return_Date,Days_Late,Return_Status,Fine_Amount
0,TXN001,STU011,Sanjay Patel,Mechanical Engineering,B002,Data Science Fundamentals,Data Science,410,2026-01-11,2026-01-25,2026-01-27,2,Late,10
1,TXN002,STU004,Sneha Iyer,Electronics,B004,Database Management,Computer Science,360,2026-02-09,2026-02-23,2026-02-23,0,On Time,0
2,TXN003,STU011,Sanjay Patel,Mechanical Engineering,B012,Cloud Computing,Technology,460,2026-05-24,2026-06-07,2026-06-07,0,On Time,0
3,TXN004,STU010,Divya Nair,Electronics,B007,Engineering Mechanics,Engineering,280,2026-01-13,2026-01-27,2026-01-27,0,On Time,0
4,TXN005,STU002,Priya Sharma,Data Science,B004,Database Management,Computer Science,360,2026-03-05,2026-03-19,2026-03-29,10,Late,50

In [3]:
# groupby() - Divide the rows into groups to perform some calculations

df.shape

(80, 14)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  80 non-null     str
 1   Student_ID      80 non-null     str
 2   Student_Name    80 non-null     str
 3   Department      80 non-null     str
 4   Book_ID         80 non-null     str
 5   Book_Title      80 non-null     str
 6   Book_Category   80 non-null     str
 7   Book_Price      80 non-null     int64
 8   Borrow_Date     80 non-null     str
 9   Due_Date        80 non-null     str
 10  Return_Date     80 non-null     str
 11  Days_Late       80 non-null     int64
 12  Return_Status   80 non-null     str
 13  Fine_Amount     80 non-null     int64
dtypes: int64(3), str(11)
memory usage: 17.5 KB

In [8]:
df.groupby("Department")["Fine_Amount"].sum()

Department
Civil Engineering          15
Computer Science          275
Data Science              200
Electronics               405
Information Technology    315
Mechanical Engineering    180
Name: Fine_Amount, dtype: int64

In [12]:
avg_late_days = df.groupby("Department")["Days_Late"].sum()
avg_late_days

Department
Civil Engineering          3
Computer Science          55
Data Science              40
Electronics               81
Information Technology    63
Mechanical Engineering    36
Name: Days_Late, dtype: int64

In [14]:
transaction_count = df.groupby("Department")["Transaction_ID"].count()
transaction_count

Department
Civil Engineering          6
Computer Science          16
Data Science              11
Electronics               19
Information Technology    14
Mechanical Engineering    14
Name: Transaction_ID, dtype: int64

In [21]:
books = df.groupby("Book_Category")["Book_Price"].agg(["max", "min", "mean"])
books

                  max  min        mean
Book_Category
Computer Science  420  360  386.538462
Data Science      475  410  439.615385
Electronics       300  300  300.000000
Engineering       350  280  310.625000
Programming       330  320  326.666667
Technology        460  460  460.000000

In [18]:
computer_science = df.groupby(["Department", "Return_Status"])["Transaction_ID"].count()
computer_science

Department              Return_Status
Civil Engineering       Late              1
                        On Time           5
Computer Science        Late             11
                        On Time           5
Data Science            Late              5
                        On Time           6
Electronics             Late             14
                        On Time           5
Information Technology  Late             11
                        On Time           3
Mechanical Engineering  Late              8
                        On Time           6
Name: Transaction_ID, dtype: int64

In [24]:
total_fine = df.groupby(["Department", "Return_Status"])["Fine_Amount"].sum()
total_fine

Department              Return_Status
Civil Engineering       Late              15
                        On Time            0
Computer Science        Late             275
                        On Time            0
Data Science            Late             200
                        On Time            0
Electronics             Late             405
                        On Time            0
Information Technology  Late             315
                        On Time            0
Mechanical Engineering  Late             180
                        On Time            0
Name: Fine_Amount, dtype: int64

In [28]:
summary_of_transactions = df.groupby("Book_Category").agg(
    transaction = ("Transaction_ID", "count"),
    total_fine = ("Fine_Amount", "sum"),
    avg_late_days = ("Days_Late", "mean"),
    max_late_days = ("Days_Late", "max")
)

summary_of_transactions

                  transaction  total_fine  avg_late_days  max_late_days
Book_Category
Computer Science           26         380       2.923077             10
Data Science               13         245       3.769231             14
Electronics                 5         105       4.200000             10
Engineering                16         295       3.687500             10
Programming                15         180       2.400000             14
Technology                  5         185       7.400000             10