In [7]:
import pandas as pd
df = pd.read_csv(r"airline_booking.csv")
df.head()

,Booking_ID,Passenger_ID,Origin,Destination,Airline,Cabin_Code,Payment_Code,Booking_Channel,Trip_Type,Meal_Code,Travel_Month,Base_Fare,Baggage_KG,Baggage_Charge,Meal_Charge,Service_Fee,Discount_Percent,Flight_Duration_Hours,Customer_Rating
0,BK10001,PS2001,Bengaluru,Colombo,Singapore Airlines,E,CC,Website,Round Trip,NV,March,23950,10,0,350,300,20,9.4,3.5
1,BK10002,PS2002,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Website,One Way,VG,October,27735,10,0,250,300,0,6.1,5.0
2,BK10003,PS2003,Chennai,Dubai,Air India,P,CC,Website,One Way,NV,January,31827,25,1250,350,150,10,8.6,4.0
3,BK10004,PS2004,Kolkata,Singapore,IndiGo,E,UPI,Travel Agent,One Way,SF,March,17713,20,0,450,150,5,7.7,5.0
4,BK10005,PS2005,Kolkata,London,Vistara,E,CC,Website,One Way,SF,August,33327,10,0,450,150,10,4.7,5.0

---
# *Part A – GroupBy*
---

In [8]:
# 1. Total Fare by Airline - Find the total Base Fare collected by each Airline using groupby().

total_base_fare_airline = df.groupby("Airline")["Base_Fare"].sum()
total_base_fare_airline

Airline
Air India             1806938
Emirates              2028017
IndiGo                2040524
Singapore Airlines    1908215
Vistara               1965764
Name: Base_Fare, dtype: int64

In [9]:
# 2. Average Fare by Destination - Find the average Base Fare for each Destination

average_base_fare_destination = df.groupby("Destination")["Base_Fare"].mean()
average_base_fare_destination

Destination
Bangkok         20952.333333
Colombo         18476.548387
Dubai           19941.587500
Kuala Lumpur    19125.697368
London          19107.351648
Singapore       19574.063291
Name: Base_Fare, dtype: float64

In [10]:
# 3. Number of Bookings by Booking Channel - Find how many bookings were made through each: Website, Mobile App, Travel Agent

no_of_bookings_by_booking_channel = df.groupby("Booking_Channel")["Booking_ID"].count()
no_of_bookings_by_booking_channel

Booking_Channel
Mobile App      172
Travel Agent    160
Website         168
Name: Booking_ID, dtype: int64

In [11]:
# 4. Average Customer Rating by Airline - Find the average Customer Rating for each Airline

avg_cust_rating_airline = df.groupby("Airline")["Customer_Rating"].mean()
avg_cust_rating_airline

Airline
Air India             4.017442
Emirates              4.018018
IndiGo                3.956731
Singapore Airlines    3.963542
Vistara               3.927184
Name: Customer_Rating, dtype: float64

In [12]:
# 5. Airline and Booking Channel Analysis - Find the number of bookings for each Airline and Booking Channel. Use multiple columns with groupby().

no_of_bookings_airline_channel = df.groupby(["Airline", "Booking_Channel"])["Booking_ID"].count()
no_of_bookings_airline_channel

Airline             Booking_Channel
Air India           Mobile App         28
                    Travel Agent       33
                    Website            25
Emirates            Mobile App         30
                    Travel Agent       33
                    Website            48
IndiGo              Mobile App         38
                    Travel Agent       32
                    Website            34
Singapore Airlines  Mobile App         32
                    Travel Agent       31
                    Website            33
Vistara             Mobile App         44
                    Travel Agent       31
                    Website            28
Name: Booking_ID, dtype: int64

In [13]:
# 6. Airline Fare Summary For each Airline, find: Minimum Base Fare, Maximum Base Fare, Average Base Fare. Use agg().

min_max_avg_airline = df.groupby("Airline")["Base_Fare"].agg(["min", "max", "mean"])
min_max_avg_airline

                     min    max          mean
Airline
Air India           4901  34816  21010.906977
Emirates            5178  34192  18270.423423
IndiGo              5443  34885  19620.423077
Singapore Airlines  5251  34925  19877.239583
Vistara             4561  34995  19085.087379

In [14]:
# 7. Destination and Cabin Analysis. For each Destination and Cabin_Code, find the average Base Fare.

avg_base_fare_destination_cabin = df.groupby(["Destination", "Cabin_Code"])["Base_Fare"].mean()
avg_base_fare_destination_cabin

Destination   Cabin_Code
Bangkok       B             19693.777778
              E             21139.067797
              P             20976.153846
Colombo       B             19380.428571
              E             18473.285714
              P             18095.375000
Dubai         B             18362.111111
              E             21394.345455
              P             15836.187500
Kuala Lumpur  B              6784.500000
              E             20002.068966
              P             17491.500000
London        B             18733.250000
              E             19536.390625
              P             17978.565217
Singapore     B             20227.750000
              E             19861.846154
              P             18053.466667
Name: Base_Fare, dtype: float64

---
# *Part B – Map*
---

In [15]:
# 8. Convert Cabin Codes
# The Cabin_Code column contains:
# • E 
# • P 
# • B 
# Use a dictionary and map() to create a new column called:
# Cabin_Type
# Mapping:
# • E → Economy 
# • P → Premium Economy 
# • B → Business

cabin_code_mapping = {
    "E" : "Economy",
    "P" : "Premium Economy",
    "B" : "Business"
}

df["Cabin_Type"] = df["Cabin_Code"].map(cabin_code_mapping)
df

,Booking_ID,Passenger_ID,Origin,Destination,Airline,Cabin_Code,Payment_Code,Booking_Channel,Trip_Type,Meal_Code,Travel_Month,Base_Fare,Baggage_KG,Baggage_Charge,Meal_Charge,Service_Fee,Discount_Percent,Flight_Duration_Hours,Customer_Rating,Cabin_Type
0,BK10001,PS2001,Bengaluru,Colombo,Singapore Airlines,E,CC,Website,Round Trip,NV,March,23950,10,0,350,300,20,9.4,3.5,Economy
1,BK10002,PS2002,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Website,One Way,VG,October,27735,10,0,250,300,0,6.1,5.0,Economy
2,BK10003,PS2003,Chennai,Dubai,Air India,P,CC,Website,One Way,NV,January,31827,25,1250,350,150,10,8.6,4.0,Premium Economy
3,BK10004,PS2004,Kolkata,Singapore,IndiGo,E,UPI,Travel Agent,One Way,SF,March,17713,20,0,450,150,5,7.7,5.0,Economy
4,BK10005,PS2005,Kolkata,London,Vistara,E,CC,Website,One Way,SF,August,33327,10,0,450,150,10,4.7,5.0,Economy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,BK10496,PS2496,Chennai,Colombo,IndiGo,P,NB,Travel Agent,One Way,SF,June,28042,30,2500,450,200,5,10.3,4.0,Premium Economy
496,BK10497,PS2497,Delhi,Bangkok,Air India,E,UPI,Travel Agent,Round Trip,VG,April,28718,20,0,250,250,20,10.9,5.0,Economy
497,BK10498,PS2498,Kolkata,Colombo,Vistara,P,NB,Mobile App,Round Trip,NV,August,9950,25,1250,350,300,5,5.2,3.5,Premium Economy
498,BK10499,PS2499,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Mobile App,Round Trip,VG,June,23569,15,0,250,150,15,3.1,3.0,Economy
499,BK10500,PS2500,Mumbai,Singapore,IndiGo,E,NB,Mobile App,Round Trip,NV,August,17349,10,0,350,200,10,10.4,3.0,Economy

In [16]:
# 9. Convert Payment Codes
# The Payment_Code column contains:
# • UPI 
# • CC 
# • DC 
# • NB 
# Use map() to create:
# Payment_Method
# Convert the codes into meaningful payment method names.

df["Payment_Method"] = df["Payment_Code"].map({
    "UPI": "Unified Payments Interface",
    "CC": "Credit Card",
    "DC": "Debit Card",
    "NB": "Net Banking"
})

df

,Booking_ID,Passenger_ID,Origin,Destination,Airline,Cabin_Code,Payment_Code,Booking_Channel,Trip_Type,Meal_Code,...,Base_Fare,Baggage_KG,Baggage_Charge,Meal_Charge,Service_Fee,Discount_Percent,Flight_Duration_Hours,Customer_Rating,Cabin_Type,Payment_Method
0,BK10001,PS2001,Bengaluru,Colombo,Singapore Airlines,E,CC,Website,Round Trip,NV,...,23950,10,0,350,300,20,9.4,3.5,Economy,Credit Card
1,BK10002,PS2002,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Website,One Way,VG,...,27735,10,0,250,300,0,6.1,5.0,Economy,Net Banking
2,BK10003,PS2003,Chennai,Dubai,Air India,P,CC,Website,One Way,NV,...,31827,25,1250,350,150,10,8.6,4.0,Premium Economy,Credit Card
3,BK10004,PS2004,Kolkata,Singapore,IndiGo,E,UPI,Travel Agent,One Way,SF,...,17713,20,0,450,150,5,7.7,5.0,Economy,Unified Payments Interface
4,BK10005,PS2005,Kolkata,London,Vistara,E,CC,Website,One Way,SF,...,33327,10,0,450,150,10,4.7,5.0,Economy,Credit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,BK10496,PS2496,Chennai,Colombo,IndiGo,P,NB,Travel Agent,One Way,SF,...,28042,30,2500,450,200,5,10.3,4.0,Premium Economy,Net Banking
496,BK10497,PS2497,Delhi,Bangkok,Air India,E,UPI,Travel Agent,Round Trip,VG,...,28718,20,0,250,250,20,10.9,5.0,Economy,Unified Payments Interface
497,BK10498,PS2498,Kolkata,Colombo,Vistara,P,NB,Mobile App,Round Trip,NV,...,9950,25,1250,350,300,5,5.2,3.5,Premium Economy,Net Banking
498,BK10499,PS2499,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Mobile App,Round Trip,VG,...,23569,15,0,250,150,15,3.1,3.0,Economy,Net Banking
499,BK10500,PS2500,Mumbai,Singapore,IndiGo,E,NB,Mobile App,Round Trip,NV,...,17349,10,0,350,200,10,10.4,3.0,Economy,Net Banking

In [17]:
# 10. Convert Meal Codes
# Use map() on Meal_Code and create:
# Meal_Type
# Convert:
# • VG → Vegetarian 
# • NV → Non-Vegetarian 
# • SF → Special Food

df["Meal_Type"] = df["Meal_Code"].map({
    "VG" : "Vegetarian",
    "NV" : "Non-Vegetarian",
    "SF" : "Special Food"
})

df

,Booking_ID,Passenger_ID,Origin,Destination,Airline,Cabin_Code,Payment_Code,Booking_Channel,Trip_Type,Meal_Code,...,Baggage_KG,Baggage_Charge,Meal_Charge,Service_Fee,Discount_Percent,Flight_Duration_Hours,Customer_Rating,Cabin_Type,Payment_Method,Meal_Type
0,BK10001,PS2001,Bengaluru,Colombo,Singapore Airlines,E,CC,Website,Round Trip,NV,...,10,0,350,300,20,9.4,3.5,Economy,Credit Card,Non-Vegetarian
1,BK10002,PS2002,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Website,One Way,VG,...,10,0,250,300,0,6.1,5.0,Economy,Net Banking,Vegetarian
2,BK10003,PS2003,Chennai,Dubai,Air India,P,CC,Website,One Way,NV,...,25,1250,350,150,10,8.6,4.0,Premium Economy,Credit Card,Non-Vegetarian
3,BK10004,PS2004,Kolkata,Singapore,IndiGo,E,UPI,Travel Agent,One Way,SF,...,20,0,450,150,5,7.7,5.0,Economy,Unified Payments Interface,Special Food
4,BK10005,PS2005,Kolkata,London,Vistara,E,CC,Website,One Way,SF,...,10,0,450,150,10,4.7,5.0,Economy,Credit Card,Special Food
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,BK10496,PS2496,Chennai,Colombo,IndiGo,P,NB,Travel Agent,One Way,SF,...,30,2500,450,200,5,10.3,4.0,Premium Economy,Net Banking,Special Food
496,BK10497,PS2497,Delhi,Bangkok,Air India,E,UPI,Travel Agent,Round Trip,VG,...,20,0,250,250,20,10.9,5.0,Economy,Unified Payments Interface,Vegetarian
497,BK10498,PS2498,Kolkata,Colombo,Vistara,P,NB,Mobile App,Round Trip,NV,...,25,1250,350,300,5,5.2,3.5,Premium Economy,Net Banking,Non-Vegetarian
498,BK10499,PS2499,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Mobile App,Round Trip,VG,...,15,0,250,150,15,3.1,3.0,Economy,Net Banking,Vegetarian
499,BK10500,PS2500,Mumbai,Singapore,IndiGo,E,NB,Mobile App,Round Trip,NV,...,10,0,350,200,10,10.4,3.0,Economy,Net Banking,Non-Vegetarian

---
# *Part C – Apply*
---

In [18]:
# 11. Create Baggage Category

def baggage_category(kg):
    if kg <= 15:
        return "Light"
    elif kg <= 25:
        return "Medium"
    else:
        return "Heavy"

df["Baggage_Category"] = df["Baggage_KG"].apply(baggage_category)
df

,Booking_ID,Passenger_ID,Origin,Destination,Airline,Cabin_Code,Payment_Code,Booking_Channel,Trip_Type,Meal_Code,...,Baggage_Charge,Meal_Charge,Service_Fee,Discount_Percent,Flight_Duration_Hours,Customer_Rating,Cabin_Type,Payment_Method,Meal_Type,Baggage_Category
0,BK10001,PS2001,Bengaluru,Colombo,Singapore Airlines,E,CC,Website,Round Trip,NV,...,0,350,300,20,9.4,3.5,Economy,Credit Card,Non-Vegetarian,Light
1,BK10002,PS2002,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Website,One Way,VG,...,0,250,300,0,6.1,5.0,Economy,Net Banking,Vegetarian,Light
2,BK10003,PS2003,Chennai,Dubai,Air India,P,CC,Website,One Way,NV,...,1250,350,150,10,8.6,4.0,Premium Economy,Credit Card,Non-Vegetarian,Medium
3,BK10004,PS2004,Kolkata,Singapore,IndiGo,E,UPI,Travel Agent,One Way,SF,...,0,450,150,5,7.7,5.0,Economy,Unified Payments Interface,Special Food,Medium
4,BK10005,PS2005,Kolkata,London,Vistara,E,CC,Website,One Way,SF,...,0,450,150,10,4.7,5.0,Economy,Credit Card,Special Food,Light
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,BK10496,PS2496,Chennai,Colombo,IndiGo,P,NB,Travel Agent,One Way,SF,...,2500,450,200,5,10.3,4.0,Premium Economy,Net Banking,Special Food,Heavy
496,BK10497,PS2497,Delhi,Bangkok,Air India,E,UPI,Travel Agent,Round Trip,VG,...,0,250,250,20,10.9,5.0,Economy,Unified Payments Interface,Vegetarian,Medium
497,BK10498,PS2498,Kolkata,Colombo,Vistara,P,NB,Mobile App,Round Trip,NV,...,1250,350,300,5,5.2,3.5,Premium Economy,Net Banking,Non-Vegetarian,Medium
498,BK10499,PS2499,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Mobile App,Round Trip,VG,...,0,250,150,15,3.1,3.0,Economy,Net Banking,Vegetarian,Light
499,BK10500,PS2500,Mumbai,Singapore,IndiGo,E,NB,Mobile App,Round Trip,NV,...,0,350,200,10,10.4,3.0,Economy,Net Banking,Non-Vegetarian,Light

In [19]:
# 12. Create Flight Category

def flight_category(hours):
    if hours < 3:
        return "Short Flight"
    elif hours <= 7:
        return "Medium Flight"
    else:
        return "Long Flight"

df["Flight_Category"] = df["Flight_Duration_Hours"].apply(flight_category)
df

,Booking_ID,Passenger_ID,Origin,Destination,Airline,Cabin_Code,Payment_Code,Booking_Channel,Trip_Type,Meal_Code,...,Meal_Charge,Service_Fee,Discount_Percent,Flight_Duration_Hours,Customer_Rating,Cabin_Type,Payment_Method,Meal_Type,Baggage_Category,Flight_Category
0,BK10001,PS2001,Bengaluru,Colombo,Singapore Airlines,E,CC,Website,Round Trip,NV,...,350,300,20,9.4,3.5,Economy,Credit Card,Non-Vegetarian,Light,Long Flight
1,BK10002,PS2002,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Website,One Way,VG,...,250,300,0,6.1,5.0,Economy,Net Banking,Vegetarian,Light,Medium Flight
2,BK10003,PS2003,Chennai,Dubai,Air India,P,CC,Website,One Way,NV,...,350,150,10,8.6,4.0,Premium Economy,Credit Card,Non-Vegetarian,Medium,Long Flight
3,BK10004,PS2004,Kolkata,Singapore,IndiGo,E,UPI,Travel Agent,One Way,SF,...,450,150,5,7.7,5.0,Economy,Unified Payments Interface,Special Food,Medium,Long Flight
4,BK10005,PS2005,Kolkata,London,Vistara,E,CC,Website,One Way,SF,...,450,150,10,4.7,5.0,Economy,Credit Card,Special Food,Light,Medium Flight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,BK10496,PS2496,Chennai,Colombo,IndiGo,P,NB,Travel Agent,One Way,SF,...,450,200,5,10.3,4.0,Premium Economy,Net Banking,Special Food,Heavy,Long Flight
496,BK10497,PS2497,Delhi,Bangkok,Air India,E,UPI,Travel Agent,Round Trip,VG,...,250,250,20,10.9,5.0,Economy,Unified Payments Interface,Vegetarian,Medium,Long Flight
497,BK10498,PS2498,Kolkata,Colombo,Vistara,P,NB,Mobile App,Round Trip,NV,...,350,300,5,5.2,3.5,Premium Economy,Net Banking,Non-Vegetarian,Medium,Medium Flight
498,BK10499,PS2499,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Mobile App,Round Trip,VG,...,250,150,15,3.1,3.0,Economy,Net Banking,Vegetarian,Light,Medium Flight
499,BK10500,PS2500,Mumbai,Singapore,IndiGo,E,NB,Mobile App,Round Trip,NV,...,350,200,10,10.4,3.0,Economy,Net Banking,Non-Vegetarian,Light,Long Flight

In [20]:
# 13. Create Fare Level
df["Fare_Level"] = df["Base_Fare"].apply(
    lambda x: "High Fare" if x >= 25000 else "Normal Fare"
)

df

,Booking_ID,Passenger_ID,Origin,Destination,Airline,Cabin_Code,Payment_Code,Booking_Channel,Trip_Type,Meal_Code,...,Service_Fee,Discount_Percent,Flight_Duration_Hours,Customer_Rating,Cabin_Type,Payment_Method,Meal_Type,Baggage_Category,Flight_Category,Fare_Level
0,BK10001,PS2001,Bengaluru,Colombo,Singapore Airlines,E,CC,Website,Round Trip,NV,...,300,20,9.4,3.5,Economy,Credit Card,Non-Vegetarian,Light,Long Flight,Normal Fare
1,BK10002,PS2002,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Website,One Way,VG,...,300,0,6.1,5.0,Economy,Net Banking,Vegetarian,Light,Medium Flight,High Fare
2,BK10003,PS2003,Chennai,Dubai,Air India,P,CC,Website,One Way,NV,...,150,10,8.6,4.0,Premium Economy,Credit Card,Non-Vegetarian,Medium,Long Flight,High Fare
3,BK10004,PS2004,Kolkata,Singapore,IndiGo,E,UPI,Travel Agent,One Way,SF,...,150,5,7.7,5.0,Economy,Unified Payments Interface,Special Food,Medium,Long Flight,Normal Fare
4,BK10005,PS2005,Kolkata,London,Vistara,E,CC,Website,One Way,SF,...,150,10,4.7,5.0,Economy,Credit Card,Special Food,Light,Medium Flight,High Fare
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,BK10496,PS2496,Chennai,Colombo,IndiGo,P,NB,Travel Agent,One Way,SF,...,200,5,10.3,4.0,Premium Economy,Net Banking,Special Food,Heavy,Long Flight,High Fare
496,BK10497,PS2497,Delhi,Bangkok,Air India,E,UPI,Travel Agent,Round Trip,VG,...,250,20,10.9,5.0,Economy,Unified Payments Interface,Vegetarian,Medium,Long Flight,High Fare
497,BK10498,PS2498,Kolkata,Colombo,Vistara,P,NB,Mobile App,Round Trip,NV,...,300,5,5.2,3.5,Premium Economy,Net Banking,Non-Vegetarian,Medium,Medium Flight,Normal Fare
498,BK10499,PS2499,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Mobile App,Round Trip,VG,...,150,15,3.1,3.0,Economy,Net Banking,Vegetarian,Light,Medium Flight,Normal Fare
499,BK10500,PS2500,Mumbai,Singapore,IndiGo,E,NB,Mobile App,Round Trip,NV,...,200,10,10.4,3.0,Economy,Net Banking,Non-Vegetarian,Light,Long Flight,Normal Fare

In [21]:
# 14. Create Rating Level

df["Rating Level"] = df["Customer_Rating"].apply(
    lambda x: "Excellent" if x >= 4.5 else "Needs Improvement"
)

df

,Booking_ID,Passenger_ID,Origin,Destination,Airline,Cabin_Code,Payment_Code,Booking_Channel,Trip_Type,Meal_Code,...,Discount_Percent,Flight_Duration_Hours,Customer_Rating,Cabin_Type,Payment_Method,Meal_Type,Baggage_Category,Flight_Category,Fare_Level,Rating Level
0,BK10001,PS2001,Bengaluru,Colombo,Singapore Airlines,E,CC,Website,Round Trip,NV,...,20,9.4,3.5,Economy,Credit Card,Non-Vegetarian,Light,Long Flight,Normal Fare,Needs Improvement
1,BK10002,PS2002,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Website,One Way,VG,...,0,6.1,5.0,Economy,Net Banking,Vegetarian,Light,Medium Flight,High Fare,Excellent
2,BK10003,PS2003,Chennai,Dubai,Air India,P,CC,Website,One Way,NV,...,10,8.6,4.0,Premium Economy,Credit Card,Non-Vegetarian,Medium,Long Flight,High Fare,Needs Improvement
3,BK10004,PS2004,Kolkata,Singapore,IndiGo,E,UPI,Travel Agent,One Way,SF,...,5,7.7,5.0,Economy,Unified Payments Interface,Special Food,Medium,Long Flight,Normal Fare,Excellent
4,BK10005,PS2005,Kolkata,London,Vistara,E,CC,Website,One Way,SF,...,10,4.7,5.0,Economy,Credit Card,Special Food,Light,Medium Flight,High Fare,Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,BK10496,PS2496,Chennai,Colombo,IndiGo,P,NB,Travel Agent,One Way,SF,...,5,10.3,4.0,Premium Economy,Net Banking,Special Food,Heavy,Long Flight,High Fare,Needs Improvement
496,BK10497,PS2497,Delhi,Bangkok,Air India,E,UPI,Travel Agent,Round Trip,VG,...,20,10.9,5.0,Economy,Unified Payments Interface,Vegetarian,Medium,Long Flight,High Fare,Excellent
497,BK10498,PS2498,Kolkata,Colombo,Vistara,P,NB,Mobile App,Round Trip,NV,...,5,5.2,3.5,Premium Economy,Net Banking,Non-Vegetarian,Medium,Medium Flight,Normal Fare,Needs Improvement
498,BK10499,PS2499,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Mobile App,Round Trip,VG,...,15,3.1,3.0,Economy,Net Banking,Vegetarian,Light,Medium Flight,Normal Fare,Needs Improvement
499,BK10500,PS2500,Mumbai,Singapore,IndiGo,E,NB,Mobile App,Round Trip,NV,...,10,10.4,3.0,Economy,Net Banking,Non-Vegetarian,Light,Long Flight,Normal Fare,Needs Improvement

In [22]:
# 15. Calculate Total Booking Cost

df["Total_Booking_Cost"] = df.apply(lambda row: row["Base_Fare"] + row["Meal_Charge"] + row["Service_Fee"], axis=1)
df

,Booking_ID,Passenger_ID,Origin,Destination,Airline,Cabin_Code,Payment_Code,Booking_Channel,Trip_Type,Meal_Code,...,Flight_Duration_Hours,Customer_Rating,Cabin_Type,Payment_Method,Meal_Type,Baggage_Category,Flight_Category,Fare_Level,Rating Level,Total_Booking_Cost
0,BK10001,PS2001,Bengaluru,Colombo,Singapore Airlines,E,CC,Website,Round Trip,NV,...,9.4,3.5,Economy,Credit Card,Non-Vegetarian,Light,Long Flight,Normal Fare,Needs Improvement,24600
1,BK10002,PS2002,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Website,One Way,VG,...,6.1,5.0,Economy,Net Banking,Vegetarian,Light,Medium Flight,High Fare,Excellent,28285
2,BK10003,PS2003,Chennai,Dubai,Air India,P,CC,Website,One Way,NV,...,8.6,4.0,Premium Economy,Credit Card,Non-Vegetarian,Medium,Long Flight,High Fare,Needs Improvement,32327
3,BK10004,PS2004,Kolkata,Singapore,IndiGo,E,UPI,Travel Agent,One Way,SF,...,7.7,5.0,Economy,Unified Payments Interface,Special Food,Medium,Long Flight,Normal Fare,Excellent,18313
4,BK10005,PS2005,Kolkata,London,Vistara,E,CC,Website,One Way,SF,...,4.7,5.0,Economy,Credit Card,Special Food,Light,Medium Flight,High Fare,Excellent,33927
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,BK10496,PS2496,Chennai,Colombo,IndiGo,P,NB,Travel Agent,One Way,SF,...,10.3,4.0,Premium Economy,Net Banking,Special Food,Heavy,Long Flight,High Fare,Needs Improvement,28692
496,BK10497,PS2497,Delhi,Bangkok,Air India,E,UPI,Travel Agent,Round Trip,VG,...,10.9,5.0,Economy,Unified Payments Interface,Vegetarian,Medium,Long Flight,High Fare,Excellent,29218
497,BK10498,PS2498,Kolkata,Colombo,Vistara,P,NB,Mobile App,Round Trip,NV,...,5.2,3.5,Premium Economy,Net Banking,Non-Vegetarian,Medium,Medium Flight,Normal Fare,Needs Improvement,10600
498,BK10499,PS2499,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Mobile App,Round Trip,VG,...,3.1,3.0,Economy,Net Banking,Vegetarian,Light,Medium Flight,Normal Fare,Needs Improvement,23969
499,BK10500,PS2500,Mumbai,Singapore,IndiGo,E,NB,Mobile App,Round Trip,NV,...,10.4,3.0,Economy,Net Banking,Non-Vegetarian,Light,Long Flight,Normal Fare,Needs Improvement,17899

In [23]:
# 16. Calculate Discount Amount

def discount_amount(row):
    return row["Base_Fare"] * row["Discount_Percent"] / 100

df["Discount_Amount"] = df.apply(discount_amount, axis=1)

df

,Booking_ID,Passenger_ID,Origin,Destination,Airline,Cabin_Code,Payment_Code,Booking_Channel,Trip_Type,Meal_Code,...,Customer_Rating,Cabin_Type,Payment_Method,Meal_Type,Baggage_Category,Flight_Category,Fare_Level,Rating Level,Total_Booking_Cost,Discount_Amount
0,BK10001,PS2001,Bengaluru,Colombo,Singapore Airlines,E,CC,Website,Round Trip,NV,...,3.5,Economy,Credit Card,Non-Vegetarian,Light,Long Flight,Normal Fare,Needs Improvement,24600,4790.00
1,BK10002,PS2002,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Website,One Way,VG,...,5.0,Economy,Net Banking,Vegetarian,Light,Medium Flight,High Fare,Excellent,28285,0.00
2,BK10003,PS2003,Chennai,Dubai,Air India,P,CC,Website,One Way,NV,...,4.0,Premium Economy,Credit Card,Non-Vegetarian,Medium,Long Flight,High Fare,Needs Improvement,32327,3182.70
3,BK10004,PS2004,Kolkata,Singapore,IndiGo,E,UPI,Travel Agent,One Way,SF,...,5.0,Economy,Unified Payments Interface,Special Food,Medium,Long Flight,Normal Fare,Excellent,18313,885.65
4,BK10005,PS2005,Kolkata,London,Vistara,E,CC,Website,One Way,SF,...,5.0,Economy,Credit Card,Special Food,Light,Medium Flight,High Fare,Excellent,33927,3332.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,BK10496,PS2496,Chennai,Colombo,IndiGo,P,NB,Travel Agent,One Way,SF,...,4.0,Premium Economy,Net Banking,Special Food,Heavy,Long Flight,High Fare,Needs Improvement,28692,1402.10
496,BK10497,PS2497,Delhi,Bangkok,Air India,E,UPI,Travel Agent,Round Trip,VG,...,5.0,Economy,Unified Payments Interface,Vegetarian,Medium,Long Flight,High Fare,Excellent,29218,5743.60
497,BK10498,PS2498,Kolkata,Colombo,Vistara,P,NB,Mobile App,Round Trip,NV,...,3.5,Premium Economy,Net Banking,Non-Vegetarian,Medium,Medium Flight,Normal Fare,Needs Improvement,10600,497.50
498,BK10499,PS2499,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Mobile App,Round Trip,VG,...,3.0,Economy,Net Banking,Vegetarian,Light,Medium Flight,Normal Fare,Needs Improvement,23969,3535.35
499,BK10500,PS2500,Mumbai,Singapore,IndiGo,E,NB,Mobile App,Round Trip,NV,...,3.0,Economy,Net Banking,Non-Vegetarian,Light,Long Flight,Normal Fare,Needs Improvement,17899,1734.90

In [24]:
#17. Calculate Final Fare
def final_fare(row):
    return (row["Base_Fare"]
            + row["Baggage_Charge"]
            + row["Meal_Charge"]
            + row["Service_Fee"]
            - row["Discount_Amount"])

df["Final_Fare"] = df.apply(final_fare, axis=1)

df.head(10)

,Booking_ID,Passenger_ID,Origin,Destination,Airline,Cabin_Code,Payment_Code,Booking_Channel,Trip_Type,Meal_Code,...,Cabin_Type,Payment_Method,Meal_Type,Baggage_Category,Flight_Category,Fare_Level,Rating Level,Total_Booking_Cost,Discount_Amount,Final_Fare
0,BK10001,PS2001,Bengaluru,Colombo,Singapore Airlines,E,CC,Website,Round Trip,NV,...,Economy,Credit Card,Non-Vegetarian,Light,Long Flight,Normal Fare,Needs Improvement,24600,4790.00,19810.00
1,BK10002,PS2002,Hyderabad,Kuala Lumpur,IndiGo,E,NB,Website,One Way,VG,...,Economy,Net Banking,Vegetarian,Light,Medium Flight,High Fare,Excellent,28285,0.00,28285.00
2,BK10003,PS2003,Chennai,Dubai,Air India,P,CC,Website,One Way,NV,...,Premium Economy,Credit Card,Non-Vegetarian,Medium,Long Flight,High Fare,Needs Improvement,32327,3182.70,30394.30
3,BK10004,PS2004,Kolkata,Singapore,IndiGo,E,UPI,Travel Agent,One Way,SF,...,Economy,Unified Payments Interface,Special Food,Medium,Long Flight,Normal Fare,Excellent,18313,885.65,17427.35
4,BK10005,PS2005,Kolkata,London,Vistara,E,CC,Website,One Way,SF,...,Economy,Credit Card,Special Food,Light,Medium Flight,High Fare,Excellent,33927,3332.70,30594.30
5,BK10006,PS2006,Kolkata,Bangkok,Singapore Airlines,E,DC,Mobile App,One Way,VG,...,Economy,Debit Card,Vegetarian,Light,Medium Flight,High Fare,Needs Improvement,25973,1276.15,24696.85
6,BK10007,PS2007,Delhi,Singapore,Air India,E,CC,Travel Agent,Round Trip,NV,...,Economy,Credit Card,Non-Vegetarian,Medium,Long Flight,Normal Fare,Needs Improvement,16339,0.00,16339.00
7,BK10008,PS2008,Delhi,Kuala Lumpur,Vistara,E,CC,Travel Agent,Round Trip,VG,...,Economy,Credit Card,Vegetarian,Heavy,Long Flight,Normal Fare,Needs Improvement,23489,2303.90,23685.10
8,BK10009,PS2009,Mumbai,Singapore,Vistara,B,CC,Mobile App,One Way,NV,...,Business,Credit Card,Non-Vegetarian,Light,Long Flight,High Fare,Needs Improvement,31621,3102.10,28518.90
9,BK10010,PS2010,Kolkata,Singapore,Emirates,B,UPI,Travel Agent,One Way,VG,...,Business,Unified Payments Interface,Vegetarian,Medium,Medium Flight,Normal Fare,Needs Improvement,15273,2944.60,13578.40