In [2]:
# Series - One dimensional Data

import pandas as pd

attendance = pd.Series([98,34,255,32], index = [1, 2, 3, 4])
print(attendance)

1     98
2     34
3    255
4     32
dtype: int64

In [3]:
# Dataframe - Two Dimensional Data

students = {
    "Student_ID" : ["ST101", "ST102", "ST103"],
    "Name" : ["Atheeq", "Abdur", "Hari"],
    "Course" : ["DL", "CN", "UI"]
}

print(students)

# Convert dict to data frame - DataFrame()
data = pd.DataFrame(students, index = [1, 2, 3])
data

{'Student_ID': ['ST101', 'ST102', 'ST103'], 'Name': ['Atheeq', 'Abdur', 'Hari'], 'Course': ['DL', 'CN', 'UI']}

  Student_ID    Name Course
1      ST101  Atheeq     DL
2      ST102   Abdur     CN
3      ST103    Hari     UI

In [ ]:
data = pd.DataFrame({
    "Student_ID" : ["ST101", "ST102", "ST103"],
    "Name" : ["Atheeq", "Abdur", "Hari"],
    "Course" : ["DL", "CN", "UI/UX"]
})
data

  Student_ID    Name Course
0      ST101  Atheeq     DL
1      ST102   Abdur     CN
2      ST103    Hari  UI/UX

In [5]:
data = pd.DataFrame([
    {"name": "Atheeq", "age": 24},
    {"name": "Rahaman", "age": 25}
])

data

      name  age
0   Atheeq   24
1  Rahaman   25

In [6]:
data = pd.read_csv(r"C:/Users/Asus/Downloads/business_sample_csv.csv")
data

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23215,2025,all,All Industries,j_Grand_Total,Salaries and wages paid,160833,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23216,2025,all,All Industries,j_Grand_Total,"Sales, government funding, grants and subsidies",854561,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23217,2025,all,All Industries,j_Grand_Total,Total assets,3068548,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23218,2025,all,All Industries,j_Grand_Total,Total expenditure,867750,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23219,2025,all,All Industries,j_Grand_Total,Total income,976077,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data = pd.read_csv(r"C:/Users/Asus/Downloads/sales.csv")
data

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
0,10001,1023,Customer_1220,Chennai,West,Teacher,Headphones,Product_055,Mobile App,Debit Card,...,15,4.5,11.0,20,2025-12-16,135686.88,20353.03,115333.85,True,Slow
1,10002,1194,Customer_1120,Bengaluru,North,Business,Camera,Product_023,Online,Debit Card,...,15,2.0,10.0,22,2025-10-15,41597.03,6239.55,35357.48,False,Normal
2,10003,1164,Customer_1247,Pune,South,Professional,Headphones,Product_022,Online,UPI,...,20,3.0,13.0,56,2025-12-28,5869.60,1173.92,4695.68,False,Slow
3,10004,1110,Customer_1191,Bengaluru,North,Teacher,Mouse,Product_011,Partner,Credit Card,...,5,1.1,11.0,29,2025-07-29,117873.48,5893.67,111979.81,True,Slow
4,10005,1109,Customer_1163,Trichy,Central,Teacher,Keyboard,Product_001,Partner,Debit Card,...,20,1.0,4.0,21,2025-10-04,364887.25,72977.45,291909.80,True,Fast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,10831,1062,Customer_1139,Mumbai,Central,Business,Headphones,Product_021,Mobile App,Debit Card,...,10,4.2,1.0,63,2025-12-09,355710.45,35571.04,320139.41,True,Fast
1208,10751,1241,Customer_1229,Pune,North,Teacher,Printer,Product_051,Partner,Cash,...,0,4.8,8.0,34,2025-07-27,394035.55,0.00,394035.55,True,Normal
1209,10047,1112,Customer_1215,Pune,North,Freelancer,Mobile,Product_012,Store,Credit Card,...,20,2.1,12.0,46,2025-12-05,105552.08,21110.42,84441.66,False,Slow
1210,11133,1199,Customer_1068,Chennai,Central,Professional,Printer,Product_058,Mobile App,Credit Card,...,30,2.9,8.0,41,2025-12-12,20187.00,6056.10,14130.90,False,Normal
1211,10129,1144,Customer_1169,Chennai,West,Student,Monitor,Product_032,Partner,Cash,...,5,2.1,12.0,37,2025-09-06,167883.65,8394.18,159489.47,True,Slow

In [8]:
data.shape

(1212, 23)

In [9]:
data.columns

Index(['order_id', 'customer_id', 'customer_name', 'city', 'region',
       'customer_segment', 'product_category', 'product_name', 'sales_channel',
       'payment_method', 'order_status', 'quantity', 'unit_price',
       'discount_pct', 'rating', 'delivery_days', 'customer_age', 'order_date',
       'gross_amount', 'discount_amount', 'net_amount', 'is_high_value',
       'delivery_status'],
      dtype='str')

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1212 non-null   int64
 1   customer_id       1212 non-null   int64
 2   customer_name     1212 non-null   str
 3   city              1212 non-null   str
 4   region            1212 non-null   str
 5   customer_segment  1188 non-null   str
 6   product_category  1212 non-null   str
 7   product_name      1212 non-null   str
 8   sales_channel     1212 non-null   str
 9   payment_method    1194 non-null   str
 10  order_status      1212 non-null   str
 11  quantity          1212 non-null   int64
 12  unit_price        1212 non-null   float64
 13  discount_pct      1212 non-null   int64
 14  rating            1182 non-null   float64
 15  delivery_days     1193 non-null   float64
 16  customer_age      1212 non-null   int64
 17  order_date        1212 non-null   str
 18  gross_amount      1212 non-null   float64
 19  discount_amount   1212 non-null   float64
 20  net_amount        1212 non-null   float64
 21  is_high_value     1212 non-null   bool
 22  delivery_status   1212 non-null   str
dtypes: bool(1), float64(6), int64(5), str(11)
memory usage: 316.0 KB

In [19]:
data.sample(5, random_state=42)

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
801,10802,1076,Customer_1016,Delhi,South,Freelancer,Laptop,Product_058,Mobile App,Credit Card,...,5,3.4,11.0,53,2025-10-06,431115.28,21555.76,409559.52,True,Slow
677,10678,1022,Customer_1225,Mumbai,Central,Teacher,Tablet,Product_040,Online,Credit Card,...,25,3.8,8.0,40,2025-05-12,93378.43,23344.61,70033.82,False,Normal
43,10044,1089,Customer_1123,Madurai,West,Student,Printer,Product_023,Online,Credit Card,...,25,3.4,11.0,23,2025-02-08,196995.42,49248.86,147746.56,True,Slow
990,10991,1086,Customer_1091,Madurai,North,Teacher,Mouse,Product_017,Store,Cash,...,15,2.2,NaN,43,2025-09-09,80381.10,12057.16,68323.94,False,Normal
70,10071,1199,Customer_1093,Mumbai,South,Student,Mobile,Product_025,Mobile App,Net Banking,...,20,1.9,10.0,22,2025-09-01,309818.52,61963.70,247854.82,True,Normal

In [23]:
data.describe(include = 'all')

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
count,1212.000000,1212.000000,1212,1212,1212,1188,1212,1212,1212,1194,...,1212.000000,1182.000000,1193.000000,1212.000000,1212,1212.000000,1212.000000,1212.000000,1212,1212
unique,NaN,NaN,246,10,4,5,10,80,4,5,...,NaN,NaN,NaN,NaN,345,NaN,NaN,NaN,2,3
top,NaN,NaN,Customer_1099,Coimbatore,West,Business,Laptop,Product_023,Partner,Credit Card,...,NaN,NaN,NaN,NaN,2025-05-05,NaN,NaN,NaN,True,Normal
freq,NaN,NaN,13,137,326,248,141,23,307,264,...,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,683,456
mean,10600.170792,1126.727723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.843234,2.978765,7.629505,41.513201,NaN,180479.045536,26872.002979,153607.042558,NaN,NaN
std,346.852941,71.939098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.953244,1.176238,3.976044,13.862150,NaN,140306.869506,30593.815288,121307.499858,NaN,NaN
min,10001.000000,1002.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,1.000000,1.000000,18.000000,NaN,769.900000,0.000000,646.510000,NaN,NaN
25%,10299.750000,1064.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,1.900000,4.000000,29.000000,NaN,71039.662500,4586.985000,58425.442500,NaN,NaN
50%,10600.500000,1127.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.000000,3.000000,8.000000,41.000000,NaN,141748.400000,15757.250000,121184.420000,NaN,NaN
75%,10900.250000,1190.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.000000,3.975000,11.000000,54.000000,NaN,260352.480000,39483.270000,223632.235000,NaN,NaN
max,11200.000000,1250.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.000000,5.000000,14.000000,65.000000,NaN,595177.800000,158840.000000,595177.800000,NaN,NaN

In [30]:
city = data["city"]
city[0:2]
city.head()

0      Chennai
1    Bengaluru
2         Pune
3    Bengaluru
4       Trichy
Name: city, dtype: str

In [34]:
data.city[0:3]

0      Chennai
1    Bengaluru
2         Pune
Name: city, dtype: str